# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ishank Gulati
tagline:             'Robotics, Machine learning, Computer Vision'         
paginate:            1
baseurl:             http://ishank08.github.io/

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ishank Gulati
  url:               https://twitter.com/mdo
  email:             gulati.ishank@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ishank08/ishank08.github.io
